### ISSUE TITLE
Rename plugin to `weebase.py`

### ISSUE THREAD

**Issue by saro** [c3r34lk1ll3r/wee_keybase#1]
Hello,

I'm at the moment working on a fork of this repo at https://github.com/saro/weebase

I have few changes I would like translate as PR to this project (if you are still willing to maintain it) but before doing anything I'm wondering if you are ok with renaming of the plugin from `keybase.py` to `weebase.py`.

This would make it more consistent with the project.

**Comment by c3r34lk1ll3r** [comment]
Hi,

I changed the name as requested. Indeed, it makes more sense.
